/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Page */
        get: operations["demo_page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/gmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect Gmail */
        delete: operations["disconnect_gmail_account_gmail_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inbox Search Endpoint
         * @description Natural language search and Q&A over masked emails and policy documents.
         */
        post: operations["inbox_search_endpoint_api_search_inbox_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Trail */
        get: operations["get_audit_trail_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finish Google Sign In */
        get: operations["finish_google_sign_in_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google Sign In */
        get: operations["start_google_sign_in_auth_google_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_auth_session_get"];
        put?: never;
        post?: never;
        /** Sign Out */
        delete: operations["sign_out_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Current Session */
        post: operations["refresh_current_session_auth_session_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Documents */
        get: operations["get_documents_documents_get"];
        put?: never;
        /** Add Document */
        post: operations["add_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        /**
         * Remove Document
         * @description Chunks and both kinds of vector go with it (ON DELETE CASCADE).
         */
        delete: operations["remove_document_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Emails */
        get: operations["emails_emails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/by-thread/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Email For Thread Route */
        get: operations["email_for_thread_route_emails_by_thread__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Email Detail Route */
        get: operations["email_detail_route_emails__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{message_id}/confirm-sender": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Sender Route */
        post: operations["confirm_sender_route_emails__message_id__confirm_sender_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{message_id}/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refine Email Route */
        post: operations["refine_email_route_emails__message_id__refine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{message_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Email Route */
        post: operations["regenerate_email_route_emails__message_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{message_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Email Route */
        post: operations["send_email_route_emails__message_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{message_id}/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Translate Email Route */
        post: operations["translate_email_route_emails__message_id__translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holding-replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Route */
        get: operations["list_route_holding_replies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holding-replies/{reply_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel Route
         * @description Cancel one still waiting. 404 for someone else's, 409 once sent or already cancelled.
         */
        delete: operations["cancel_route_holding_replies__reply_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/writing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Style */
        get: operations["get_style_profile_writing_get"];
        put?: never;
        post?: never;
        /**
         * Delete Everything
         * @description Description, examples, habits, hidden markers, every recorded draft/sent pair and past reply.
         */
        delete: operations["delete_everything_profile_writing_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/writing/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Description
         * @description Masked before it is stored; the response shows exactly what the AI will be given.
         */
        put: operations["put_description_profile_writing_description_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/writing/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Example */
        post: operations["add_example_profile_writing_examples_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/writing/examples/{example_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Example */
        delete: operations["delete_example_profile_writing_examples__example_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/writing/habits/{habit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Habit
         * @description Hidden for good: the row stays as a marker so relearning never brings the habit back.
         */
        delete: operations["delete_habit_profile_writing_habits__habit_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/writing/learning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Learning */
        put: operations["put_learning_profile_writing_learning_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/holding-reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings Route */
        get: operations["get_settings_route_settings_holding_reply_get"];
        /** Put Settings Route */
        put: operations["put_settings_route_settings_holding_reply_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/private-mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Private Mode */
        get: operations["get_private_mode_settings_private_mode_get"];
        /** Put Private Mode */
        put: operations["put_private_mode_settings_private_mode_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/scan-reading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan Reading */
        get: operations["get_scan_reading_settings_scan_reading_get"];
        /** Put Scan Reading */
        put: operations["put_scan_reading_settings_scan_reading_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Info */
        get: operations["system_info_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActiveWhen
         * @enum {string}
         */
        ActiveWhen: "outside_hours" | "leave" | "always";
        /** AskRequest */
        AskRequest: {
            /**
             * K
             * @default 5
             */
            k: number;
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources: components["schemas"]["ContextChunk"][];
        };
        /**
         * Audience
         * @enum {string}
         */
        Audience: "correspondents" | "domain" | "everyone";
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Createdat */
            createdAt: string;
            /** Currenthash */
            currentHash: string | null;
            /** Fields */
            fields: {
                [key: string]: string | number | boolean | null;
            };
            /** Id */
            id: string;
            /** Prevhash */
            prevHash: string | null;
            /** Success */
            success: boolean | null;
            verification: components["schemas"]["Verification"];
        };
        /** AuditTrailResponse */
        AuditTrailResponse: {
            /** Events */
            events: components["schemas"]["AuditEventOut"][];
            /** Headhash */
            headHash: string | null;
            /** Ischainintact */
            isChainIntact: boolean;
            /** Totalrecords */
            totalRecords: number;
            /** Verifiedrecords */
            verifiedRecords: number;
        };
        /**
         * AuthStatus
         * @description The sender's domain check (SPF, DKIM, DMARC), read by the listener (migration 0024).
         * @enum {string}
         */
        AuthStatus: "pass" | "spoof_detected" | "unverified" | "sender_confirmed";
        /** Body_upload_document_documents_upload_post */
        Body_upload_document_documents_upload_post: {
            /** File */
            file: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** ChunkDetail */
        ChunkDetail: {
            /** Chunk Idx */
            chunk_idx: number;
            /** Content */
            content: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Section */
            section: string | null;
        };
        /**
         * ContextChunk
         * @description Seam 2 — Lane B retrieval -> Lane C generation (in-process).
         *
         *     Returned by `retrieve(masked_email, k, scope=...)`; Lane C builds its prompt from these.
         */
        ContextChunk: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Content */
            content: string;
            /** Similarity Score */
            similarity_score: number;
            /** Source Title */
            source_title: string;
        };
        /**
         * DashboardEmail
         * @description The joined email view the Lane D dashboard renders (matches Han's `Email` type).
         *
         *     Fields are camelCase to match the frontend. Lane A fills sender/subject/preview/timestamp/
         *     piiMasked, Lane B fills priority, Lane C fills aiSummary/actionItems/draftReply/criticConfidence.
         */
        DashboardEmail: {
            /** Actionitems */
            actionItems: string[];
            /** Aisummary */
            aiSummary: string;
            authStatus: components["schemas"]["AuthStatus"];
            /** Body */
            body: string;
            /**
             * Category
             * @default internal
             * @enum {string}
             */
            category: "client" | "vendor" | "internal" | "security" | "admin" | "personal";
            /** Categoryconfidence */
            categoryConfidence?: number | null;
            /** Criticconfidence */
            criticConfidence: number;
            /** Details */
            details?: components["schemas"]["Detail"][];
            /** Draftreply */
            draftReply: string;
            /** Egress */
            egress?: components["schemas"]["EgressRecord"][];
            /** Id */
            id: string;
            /**
             * Isdrafting
             * @default false
             */
            isDrafting: boolean;
            /**
             * Isread
             * @default false
             */
            isRead: boolean;
            /**
             * Masking
             * @default complete
             * @enum {string}
             */
            masking: "complete" | "pending" | "abandoned";
            /** Piimasked */
            piiMasked: boolean;
            /** Preview */
            preview: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "high" | "medium" | "low";
            /**
             * Quantities
             * @default []
             */
            quantities: components["schemas"]["QuantityView"][];
            /** Replyto */
            replyTo?: string | null;
            /** Sender */
            sender: string;
            /** Sentat */
            sentAt?: string | null;
            /** Sources */
            sources: components["schemas"]["Source"][];
            /** Subject */
            subject: string;
            /** Threadcontext */
            threadContext: components["schemas"]["ThreadMessage"][];
            /** Threadid */
            threadId?: string | null;
            /** Timestamp */
            timestamp: string;
            tone: components["schemas"]["Tone"];
        };
        /** DescriptionBody */
        DescriptionBody: {
            /** Description */
            description: string;
        };
        /**
         * Detail
         * @description A personal detail the AI saw only as its placeholder (restorable masking). Owner only.
         */
        Detail: {
            /** Kind */
            kind: string;
            /** Placeholder */
            placeholder: string;
            /** Value */
            value: string;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /** Chunk Count */
            chunk_count: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkDetail"][];
            /** Content */
            content: string;
            /** Doc Type */
            doc_type: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /** DocumentRequest */
        DocumentRequest: {
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /** Chunk Count */
            chunk_count: number;
            /** Doc Type */
            doc_type: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /**
         * EgressRecord
         * @description One prompt that left for a model, as kept by the backend (model_gateway). No text.
         */
        EgressRecord: {
            /** At */
            at: string;
            /** Caught */
            caught: number;
            /** Chars */
            chars: number;
            /** Hidden */
            hidden: {
                [key: string]: number;
            };
            /**
             * Provider
             * @enum {string}
             */
            provider: "gemini" | "local";
            /** Purpose */
            purpose: string;
        };
        /**
         * EmailPage
         * @description One page of the inbox. nextCursor goes back as ?cursor= for the next page; null on the last.
         */
        EmailPage: {
            /** Emails */
            emails: components["schemas"]["DashboardEmail"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /**
         * ExampleBody
         * @description Pasted text, or the id of one of the user's sent replies; exactly one.
         */
        ExampleBody: {
            /** Emailid */
            emailId?: string | null;
            /** Text */
            text?: string | null;
        };
        /**
         * ExampleSource
         * @enum {string}
         */
        ExampleSource: "pasted" | "sent";
        /** ExampleView */
        ExampleView: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Id */
            id: string;
            source: components["schemas"]["ExampleSource"];
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HabitView */
        HabitView: {
            /** Evidence */
            evidence: number;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            language?: components["schemas"]["Language"] | null;
            /** Outof */
            outOf: number;
            /** Value */
            value: string;
        };
        /** HoldingReplyView */
        HoldingReplyView: {
            /** Cancelledreason */
            cancelledReason: string | null;
            /** Emailid */
            emailId: string;
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Recipient */
            recipient: string;
            /**
             * Scheduledfor
             * Format: date-time
             */
            scheduledFor: string;
            /** Sentat */
            sentAt: string | null;
            /** Subject */
            subject: string;
        };
        /** InboxSearchRequest */
        InboxSearchRequest: {
            /** History */
            history?: components["schemas"]["ChatMessage"][];
            /**
             * K Docs
             * @default 3
             */
            k_docs: number;
            /**
             * K Emails
             * @default 5
             */
            k_emails: number;
            /** Query */
            query: string;
        };
        /** InboxSearchResponse */
        InboxSearchResponse: {
            /** Answer */
            answer: string;
            /**
             * Has Restored Pii
             * @default false
             */
            has_restored_pii: boolean;
            /** Intent */
            intent?: string | null;
            /** Sender Vault */
            sender_vault?: {
                [key: string]: string;
            };
            /** Sources */
            sources: components["schemas"]["SearchSource"][];
        };
        /**
         * Language
         * @enum {string}
         */
        Language: "en" | "ms" | "zh";
        /** LearningBody */
        LearningBody: {
            /** Enabled */
            enabled: boolean;
        };
        /** MeasureView */
        MeasureView: {
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /** PrivateModeBody */
        PrivateModeBody: {
            /** Enabled */
            enabled: boolean;
        };
        /** PrivateModeView */
        PrivateModeView: {
            /** Available */
            available: boolean;
            /** Enabled */
            enabled: boolean;
            /** Model */
            model: string;
            /** Search */
            search: boolean;
        };
        /**
         * QuantityView
         * @description A quantity in the body, in both unit systems. The dashboard shows whichever the reader
         *     prefers; the side matching `system` is the figure exactly as the sender wrote it.
         */
        QuantityView: {
            imperial: components["schemas"]["MeasureView"];
            metric: components["schemas"]["MeasureView"];
            /**
             * System
             * @enum {string}
             */
            system: "metric" | "imperial";
            /** Text */
            text: string;
        };
        /** RefineRequest */
        RefineRequest: {
            /** Draft */
            draft: string;
            /** Instruction */
            instruction: string;
            /** @default professional */
            tone: components["schemas"]["Tone"];
        };
        /** RegenerateRequest */
        RegenerateRequest: {
            /** @default professional */
            tone: components["schemas"]["Tone"];
        };
        /**
         * ReplyScope
         * @enum {string}
         */
        ReplyScope: "needs_reply" | "all";
        /**
         * ScanReading
         * @description Values of user_preferences.scan_reading (migration 0036); the listener mirrors them.
         * @enum {string}
         */
        ScanReading: "local" | "checked";
        /** ScanReadingBody */
        ScanReadingBody: {
            mode: components["schemas"]["ScanReading"];
        };
        /** ScanReadingView */
        ScanReadingView: {
            /** Available */
            available: boolean;
            mode: components["schemas"]["ScanReading"];
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * K
             * @default 5
             */
            k: number;
            /** Query */
            query: string;
        };
        /** SearchSource */
        SearchSource: {
            /** Id */
            id: string;
            /** Received At */
            received_at?: string | null;
            /** Snippet */
            snippet: string;
            source_type: components["schemas"]["SourceType"];
            /** Subtitle */
            subtitle: string;
            /** Title */
            title: string;
        };
        /** SendRequest */
        SendRequest: {
            /** Draft */
            draft: string;
        };
        /** SessionInfo */
        SessionInfo: {
            /** Email */
            email: string;
            /** Hasmailbox */
            hasMailbox: boolean;
            /**
             * Needsreconnect
             * @default false
             */
            needsReconnect: boolean;
        };
        /**
         * SettingsBody
         * @description The settings as the dashboard sends and receives them (camelCase, like every contract).
         */
        SettingsBody: {
            /** @default outside_hours */
            activeWhen: components["schemas"]["ActiveWhen"];
            /** @default correspondents */
            audience: components["schemas"]["Audience"];
            /**
             * Cooldowndays
             * @default 4
             */
            cooldownDays: number;
            /** @default en */
            defaultLanguage: components["schemas"]["Language"];
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Leavefrom */
            leaveFrom?: string | null;
            /** Leaveuntil */
            leaveUntil?: string | null;
            /** @default needs_reply */
            scope: components["schemas"]["ReplyScope"];
            /** Templates */
            templates?: {
                [key: string]: string;
            };
            /**
             * Timezone
             * @default Asia/Kuala_Lumpur
             */
            timezone: string;
            /** Workdays */
            workDays?: number[];
            /**
             * Workend
             * Format: time
             * @default 18:00:00
             */
            workEnd: string;
            /**
             * Workstart
             * Format: time
             * @default 09:00:00
             */
            workStart: string;
        };
        /**
         * Source
         * @description A policy passage the draft was grounded on. `excerpt` is the passage as the model saw it.
         */
        Source: {
            /** Chunkid */
            chunkId?: string | null;
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /** Label */
            label: string;
            /** Score */
            score?: number | null;
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "email" | "document";
        /**
         * SystemInfo
         * @description Non-secret runtime configuration for the dashboard's Settings view.
         *
         *     Model names and feature flags only — never keys, URLs, or credentials, since this is
         *     served to the browser.
         */
        SystemInfo: {
            /** Auth Enabled */
            auth_enabled: boolean;
            /** Auto Generate */
            auto_generate: boolean;
            /** Chat Model */
            chat_model: string;
            /** Chunk Count */
            chunk_count: number;
            /** Document Count */
            document_count: number;
            /** Embedding Dim */
            embedding_dim: number;
            /** Embedding Model */
            embedding_model: string;
            /** Generate Poll Seconds */
            generate_poll_seconds: number;
            /** Priority Model */
            priority_model: string;
        };
        /** ThreadMessage */
        ThreadMessage: {
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Isownreply
             * @default false
             */
            isOwnReply: boolean;
            /** Sender */
            sender: string;
            /** Snippet */
            snippet: string;
            /** Timestamp */
            timestamp?: string | null;
        };
        /**
         * Tone
         * @enum {string}
         */
        Tone: "professional" | "casual";
        /** TranslateRequest */
        TranslateRequest: {
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "ms" | "zh";
        };
        /** TranslateResponse */
        TranslateResponse: {
            /** Language */
            language: string;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verification
         * @enum {string}
         */
        Verification: "verified" | "tampered" | "unverifiable";
        /** WritingStyleView */
        WritingStyleView: {
            /** Description */
            description: string;
            /** Examples */
            examples: components["schemas"]["ExampleView"][];
            /** Habits */
            habits: components["schemas"]["HabitView"][];
            /** Learning */
            learning: boolean;
            /**
             * Maxexamples
             * @default 3
             */
            maxExamples: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    demo_page__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    delete_account_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    disconnect_gmail_account_gmail_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inbox_search_endpoint_api_search_inbox_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_trail_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTrailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_google_sign_in_auth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                error?: string | null;
                error_description?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                aimail_pkce?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_google_sign_in_auth_google_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    current_session_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
        };
    };
    sign_out_auth_session_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-AIMail-Client"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_current_session_auth_session_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                "X-AIMail-Client"?: string | null;
            };
            path?: never;
            cookie?: {
                aimail_session_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_documents_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
        };
    };
    add_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_document_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emails_emails_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    email_for_thread_route_emails_by_thread__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardEmail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    email_detail_route_emails__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardEmail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_sender_route_emails__message_id__confirm_sender_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardEmail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refine_email_route_emails__message_id__refine_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardEmail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_email_route_emails__message_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardEmail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_email_route_emails__message_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardEmail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_email_route_emails__message_id__translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_route_holding_replies_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingReplyView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_route_holding_replies__reply_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reply_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_style_profile_writing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritingStyleView"];
                };
            };
        };
    };
    delete_everything_profile_writing_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_description_profile_writing_description_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DescriptionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritingStyleView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_example_profile_writing_examples_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExampleBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritingStyleView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_example_profile_writing_examples__example_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                example_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_habit_profile_writing_habits__habit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_learning_profile_writing_learning_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritingStyleView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextChunk"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_route_settings_holding_reply_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBody"];
                };
            };
        };
    };
    put_settings_route_settings_holding_reply_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_private_mode_settings_private_mode_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateModeView"];
                };
            };
        };
    };
    put_private_mode_settings_private_mode_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivateModeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateModeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_reading_settings_scan_reading_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanReadingView"];
                };
            };
        };
    };
    put_scan_reading_settings_scan_reading_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanReadingBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanReadingView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_info_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
}
